# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  secret_key_base: 8e76d6c9248f05656ad370d326a8bf62c29c1354d7d48a77843dbc89263121cde7ed0b7b5c9cf2e95af09df38bd8da566c2b08eb656673a71f029ce55707bf0f
  # Google API
  client_id: 684017838666-u9265dan8g5tn9okvuqmp0tujg8l2c75.apps.googleusercontent.com
  client_secret: 68gocwiQ5CojoFs8xJnt-DUT

test:
  secret_key_base: 6adee837dfd36b038c53a105c7512b1bca354b5222fc94155075e70b7cffc06be5816559ef3f1a5cf512ad28fda727214e81ee6e4b180598c7559910c37c1db6
  # Google API
  client_id: 684017838666-u9265dan8g5tn9okvuqmp0tujg8l2c75.apps.googleusercontent.com
  client_secret: 68gocwiQ5CojoFs8xJnt-DUT

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: e6e359a05ac24b115b1bba2caaae4398f33e13c163a722400f803acfbcdf4f4478654f42163e4df1444e604c22a6d909bba470ff28ec086f5c423f2a8132abf7
  # Google API
  client_id: 684017838666-u9265dan8g5tn9okvuqmp0tujg8l2c75.apps.googleusercontent.com
  client_secret: 68gocwiQ5CojoFs8xJnt-DUT
